# ModemManager - a library to make interacting with the ModemManager daemon
# easier.
#
# (C)2018 Open Broadcast Systems Ltd
# License: MIT


from enum import IntEnum


class MMBearerIpFamily(IntEnum):
    MM_BEARER_IP_FAMILY_NONE = 0
    MM_BEARER_IP_FAMILY_IPV4 = 1 << 0
    MM_BEARER_IP_FAMILY_IPV6 = 1 << 1
    MM_BEARER_IP_FAMILY_IPV4V6 = 1 << 2
    MM_BEARER_IP_FAMILY_ANY = 0xFFFFFFFF


class MMBearerIpMethod(IntEnum):
    MM_BEARER_IP_METHOD_UNKNOWN = 0
    MM_BEARER_IP_METHOD_PPP = 1
    MM_BEARER_IP_METHOD_STATIC = 2
    MM_BEARER_IP_METHOD_DHCP = 3


class MMBearerAllowedAuth(IntEnum):
    MM_BEARER_ALLOWED_AUTH_UNKNOWN = 0
    MM_BEARER_ALLOWED_AUTH_NONE = 1 << 0
    MM_BEARER_ALLOWED_AUTH_PAP = 1 << 1
    MM_BEARER_ALLOWED_AUTH_CHAP = 1 << 2
    MM_BEARER_ALLOWED_AUTH_MSCHAP = 1 << 3
    MM_BEARER_ALLOWED_AUTH_MSCHAPV2 = 1 << 4
    MM_BEARER_ALLOWED_AUTH_EAP = 1 << 5


class MMCallDirection(IntEnum):
    MM_CALL_DIRECTION_UNKNOWN = 0
    MM_CALL_DIRECTION_INCOMING = 1
    MM_CALL_DIRECTION_OUTGOING = 2


class MMCallState(IntEnum):
    MM_CALL_STATE_UNKNOWN = 0
    MM_CALL_STATE_DIALING = 1
    MM_CALL_STATE_RINGING_OUT = 2
    MM_CALL_STATE_RINGING_IN = 3
    MM_CALL_STATE_ACTIVE = 4
    MM_CALL_STATE_HELD = 5
    MM_CALL_STATE_WAITING = 6
    MM_CALL_STATE_TERMINATED = 7


class MMCallStateReason(IntEnum):
    MM_CALL_STATE_REASON_UNKNOWN = 0
    MM_CALL_STATE_REASON_OUTGOING_STARTED = 1
    MM_CALL_STATE_REASON_INCOMING_NEW = 2
    MM_CALL_STATE_REASON_ACCEPTED = 3
    MM_CALL_STATE_REASON_TERMINATED = 4
    MM_CALL_STATE_REASON_REFUSED_OR_BUSY = 5
    MM_CALL_STATE_REASON_ERROR = 6


class MMFirmwareImageType(IntEnum):
    MM_FIRMWARE_IMAGE_TYPE_UNKNOWN = 0
    MM_FIRMWARE_IMAGE_TYPE_GENERIC = 1
    MM_FIRMWARE_IMAGE_TYPE_GOBI = 2


class MMModem3gppFacility(IntEnum):
    MM_MODEM_3GPP_FACILITY_NONE = 0
    MM_MODEM_3GPP_FACILITY_SIM = 1 << 0
    MM_MODEM_3GPP_FACILITY_FIXED_DIALING = 1 << 1
    MM_MODEM_3GPP_FACILITY_PH_SIM = 1 << 2
    MM_MODEM_3GPP_FACILITY_PH_FSIM = 1 << 3
    MM_MODEM_3GPP_FACILITY_NET_PERS = 1 << 4
    MM_MODEM_3GPP_FACILITY_NET_SUB_PERS = 1 << 5
    MM_MODEM_3GPP_FACILITY_PROVIDER_PERS = 1 << 6
    MM_MODEM_3GPP_FACILITY_CORP_PERS = 1 << 7


class MMModem3gppNetworkAvailability(IntEnum):
    MM_MODEM_3GPP_NETWORK_AVAILABILITY_UNKNOWN = 0
    MM_MODEM_3GPP_NETWORK_AVAILABILITY_AVAILABLE = 1
    MM_MODEM_3GPP_NETWORK_AVAILABILITY_CURRENT = 2
    MM_MODEM_3GPP_NETWORK_AVAILABILITY_FORBIDDEN = 3


class MMModem3gppSubscriptionState(IntEnum):
    MM_MODEM_3GPP_SUBSCRIPTION_STATE_UNKNOWN = 0
    MM_MODEM_3GPP_SUBSCRIPTION_STATE_UNPROVISIONED = 1
    MM_MODEM_3GPP_SUBSCRIPTION_STATE_PROVISIONED = 2
    MM_MODEM_3GPP_SUBSCRIPTION_STATE_OUT_OF_DATA = 3


class MMModem3gppRegistrationState(IntEnum):
    MM_MODEM_3GPP_REGISTRATION_STATE_IDLE = 0
    MM_MODEM_3GPP_REGISTRATION_STATE_HOME = 1
    MM_MODEM_3GPP_REGISTRATION_STATE_SEARCHING = 2
    MM_MODEM_3GPP_REGISTRATION_STATE_DENIED = 3
    MM_MODEM_3GPP_REGISTRATION_STATE_UNKNOWN = 4
    MM_MODEM_3GPP_REGISTRATION_STATE_ROAMING = 5
    MM_MODEM_3GPP_REGISTRATION_STATE_HOME_SMS_ONLY = 6
    MM_MODEM_3GPP_REGISTRATION_STATE_ROAMING_SMS_ONLY = 7
    MM_MODEM_3GPP_REGISTRATION_STATE_EMERGENCY_ONLY = 8
    MM_MODEM_3GPP_REGISTRATION_STATE_HOME_CSFB_NOT_PREFERRED = 9
    MM_MODEM_3GPP_REGISTRATION_STATE_ROAMING_CSFB_NOT_PREFERRED = 10


class MMModem3gppUssdSessionState(IntEnum):
    MM_MODEM_3GPP_USSD_SESSION_STATE_UNKNOWN = 0
    MM_MODEM_3GPP_USSD_SESSION_STATE_IDLE = 1
    MM_MODEM_3GPP_USSD_SESSION_STATE_ACTIVE = 2
    MM_MODEM_3GPP_USSD_SESSION_STATE_USER_RESPONSE = 3


class MMModemAccessTechnology(IntEnum):
    MM_MODEM_ACCESS_TECHNOLOGY_UNKNOWN = 0
    MM_MODEM_ACCESS_TECHNOLOGY_POTS = 1 << 0
    MM_MODEM_ACCESS_TECHNOLOGY_GSM = 1 << 1
    MM_MODEM_ACCESS_TECHNOLOGY_GSM_COMPACT = 1 << 2
    MM_MODEM_ACCESS_TECHNOLOGY_GPRS = 1 << 3
    MM_MODEM_ACCESS_TECHNOLOGY_EDGE = 1 << 4
    MM_MODEM_ACCESS_TECHNOLOGY_UMTS = 1 << 5
    MM_MODEM_ACCESS_TECHNOLOGY_HSDPA = 1 << 6
    MM_MODEM_ACCESS_TECHNOLOGY_HSUPA = 1 << 7
    MM_MODEM_ACCESS_TECHNOLOGY_HSPA = 1 << 8
    MM_MODEM_ACCESS_TECHNOLOGY_HSPA_PLUS = 1 << 9
    MM_MODEM_ACCESS_TECHNOLOGY_1XRTT = 1 << 10
    MM_MODEM_ACCESS_TECHNOLOGY_EVDO0 = 1 << 11
    MM_MODEM_ACCESS_TECHNOLOGY_EVDOA = 1 << 12
    MM_MODEM_ACCESS_TECHNOLOGY_EVDOB = 1 << 13
    MM_MODEM_ACCESS_TECHNOLOGY_LTE = 1 << 14
    MM_MODEM_ACCESS_TECHNOLOGY_ANY = 0xFFFFFFFF


class MMModemBand(IntEnum):
    MM_MODEM_BAND_UNKNOWN = 0
    # GSM/UMTS bands
    MM_MODEM_BAND_EGSM = 1
    MM_MODEM_BAND_DCS = 2
    MM_MODEM_BAND_PCS = 3
    MM_MODEM_BAND_G850 = 4
    MM_MODEM_BAND_UTRAN_1 = 5
    MM_MODEM_BAND_UTRAN_3 = 6
    MM_MODEM_BAND_UTRAN_4 = 7
    MM_MODEM_BAND_UTRAN_6 = 8
    MM_MODEM_BAND_UTRAN_5 = 9
    MM_MODEM_BAND_UTRAN_8 = 10
    MM_MODEM_BAND_UTRAN_9 = 11
    MM_MODEM_BAND_UTRAN_2 = 12
    MM_MODEM_BAND_UTRAN_7 = 13
    MM_MODEM_BAND_G450 = 14
    MM_MODEM_BAND_G480 = 15
    MM_MODEM_BAND_G750 = 16
    MM_MODEM_BAND_G380 = 17
    MM_MODEM_BAND_G410 = 18
    MM_MODEM_BAND_G710 = 19
    MM_MODEM_BAND_G810 = 20
    # LTE bands
    MM_MODEM_BAND_EUTRAN_1 = 31
    MM_MODEM_BAND_EUTRAN_2 = 32
    MM_MODEM_BAND_EUTRAN_3 = 33
    MM_MODEM_BAND_EUTRAN_4 = 34
    MM_MODEM_BAND_EUTRAN_5 = 35
    MM_MODEM_BAND_EUTRAN_6 = 36
    MM_MODEM_BAND_EUTRAN_7 = 37
    MM_MODEM_BAND_EUTRAN_8 = 38
    MM_MODEM_BAND_EUTRAN_9 = 39
    MM_MODEM_BAND_EUTRAN_10 = 40
    MM_MODEM_BAND_EUTRAN_11 = 41
    MM_MODEM_BAND_EUTRAN_12 = 42
    MM_MODEM_BAND_EUTRAN_13 = 43
    MM_MODEM_BAND_EUTRAN_14 = 44
    MM_MODEM_BAND_EUTRAN_17 = 47
    MM_MODEM_BAND_EUTRAN_18 = 48
    MM_MODEM_BAND_EUTRAN_19 = 49
    MM_MODEM_BAND_EUTRAN_20 = 50
    MM_MODEM_BAND_EUTRAN_21 = 51
    MM_MODEM_BAND_EUTRAN_22 = 52
    MM_MODEM_BAND_EUTRAN_23 = 53
    MM_MODEM_BAND_EUTRAN_24 = 54
    MM_MODEM_BAND_EUTRAN_25 = 55
    MM_MODEM_BAND_EUTRAN_26 = 56
    MM_MODEM_BAND_EUTRAN_27 = 57
    MM_MODEM_BAND_EUTRAN_28 = 58
    MM_MODEM_BAND_EUTRAN_29 = 59
    MM_MODEM_BAND_EUTRAN_30 = 60
    MM_MODEM_BAND_EUTRAN_31 = 61
    MM_MODEM_BAND_EUTRAN_32 = 62
    MM_MODEM_BAND_EUTRAN_33 = 63
    MM_MODEM_BAND_EUTRAN_34 = 64
    MM_MODEM_BAND_EUTRAN_35 = 65
    MM_MODEM_BAND_EUTRAN_36 = 66
    MM_MODEM_BAND_EUTRAN_37 = 67
    MM_MODEM_BAND_EUTRAN_38 = 68
    MM_MODEM_BAND_EUTRAN_39 = 69
    MM_MODEM_BAND_EUTRAN_40 = 70
    MM_MODEM_BAND_EUTRAN_41 = 71
    MM_MODEM_BAND_EUTRAN_42 = 72
    MM_MODEM_BAND_EUTRAN_43 = 73
    MM_MODEM_BAND_EUTRAN_44 = 74
    MM_MODEM_BAND_EUTRAN_45 = 75
    MM_MODEM_BAND_EUTRAN_46 = 76
    MM_MODEM_BAND_EUTRAN_47 = 77
    MM_MODEM_BAND_EUTRAN_48 = 78
    MM_MODEM_BAND_EUTRAN_65 = 95
    MM_MODEM_BAND_EUTRAN_66 = 96
    MM_MODEM_BAND_EUTRAN_67 = 97
    MM_MODEM_BAND_EUTRAN_68 = 98
    MM_MODEM_BAND_EUTRAN_69 = 99
    MM_MODEM_BAND_EUTRAN_70 = 100
    MM_MODEM_BAND_EUTRAN_71 = 101
    # CDMA Band Classes (see 3GPP2 C.S0057-C)
    MM_MODEM_BAND_CDMA_BC0 = 128
    MM_MODEM_BAND_CDMA_BC1 = 129
    MM_MODEM_BAND_CDMA_BC2 = 130
    MM_MODEM_BAND_CDMA_BC3 = 131
    MM_MODEM_BAND_CDMA_BC4 = 132
    MM_MODEM_BAND_CDMA_BC5 = 134
    MM_MODEM_BAND_CDMA_BC6 = 135
    MM_MODEM_BAND_CDMA_BC7 = 136
    MM_MODEM_BAND_CDMA_BC8 = 137
    MM_MODEM_BAND_CDMA_BC9 = 138
    MM_MODEM_BAND_CDMA_BC10 = 139
    MM_MODEM_BAND_CDMA_BC11 = 140
    MM_MODEM_BAND_CDMA_BC12 = 141
    MM_MODEM_BAND_CDMA_BC13 = 142
    MM_MODEM_BAND_CDMA_BC14 = 143
    MM_MODEM_BAND_CDMA_BC15 = 144
    MM_MODEM_BAND_CDMA_BC16 = 145
    MM_MODEM_BAND_CDMA_BC17 = 146
    MM_MODEM_BAND_CDMA_BC18 = 147
    MM_MODEM_BAND_CDMA_BC19 = 148
    # Additional UMTS bands:
    #   15-18 reserved
    #   23-24 reserved
    #   27-31 reserved
    MM_MODEM_BAND_UTRAN_10 = 210
    MM_MODEM_BAND_UTRAN_11 = 211
    MM_MODEM_BAND_UTRAN_12 = 212
    MM_MODEM_BAND_UTRAN_13 = 213
    MM_MODEM_BAND_UTRAN_14 = 214
    MM_MODEM_BAND_UTRAN_19 = 219
    MM_MODEM_BAND_UTRAN_20 = 220
    MM_MODEM_BAND_UTRAN_21 = 221
    MM_MODEM_BAND_UTRAN_22 = 222
    MM_MODEM_BAND_UTRAN_25 = 225
    MM_MODEM_BAND_UTRAN_26 = 226
    MM_MODEM_BAND_UTRAN_32 = 232
    # All/Any
    MM_MODEM_BAND_ANY = 256


class MMModemCapability(IntEnum):
    M_MODEM_CAPABILITY_NONE = 0
    MM_MODEM_CAPABILITY_POTS = 1 << 0
    MM_MODEM_CAPABILITY_CDMA_EVDO = 1 << 1
    MM_MODEM_CAPABILITY_GSM_UMTS = 1 << 2
    MM_MODEM_CAPABILITY_LTE = 1 << 3
    MM_MODEM_CAPABILITY_LTE_ADVANCED = 1 << 4
    MM_MODEM_CAPABILITY_IRIDIUM = 1 << 5
    MM_MODEM_CAPABILITY_ANY = 0xFFFFFFFF


class MMModemCdmaActivationState(IntEnum):
    MM_MODEM_CDMA_ACTIVATION_STATE_UNKNOWN = 0
    MM_MODEM_CDMA_ACTIVATION_STATE_NOT_ACTIVATED = 1
    MM_MODEM_CDMA_ACTIVATION_STATE_ACTIVATING = 2
    MM_MODEM_CDMA_ACTIVATION_STATE_PARTIALLY_ACTIVATED = 3
    MM_MODEM_CDMA_ACTIVATION_STATE_ACTIVATED = 4


class MMModemCdmaRegistrationState(IntEnum):
    MM_MODEM_CDMA_REGISTRATION_STATE_UNKNOWN = 0
    MM_MODEM_CDMA_REGISTRATION_STATE_REGISTERED = 1
    MM_MODEM_CDMA_REGISTRATION_STATE_HOME = 2
    MM_MODEM_CDMA_REGISTRATION_STATE_ROAMING = 3


class MMModemCdmaRmProtocol(IntEnum):
    MM_MODEM_CDMA_RM_PROTOCOL_UNKNOWN = 0
    MM_MODEM_CDMA_RM_PROTOCOL_ASYNC = 1
    MM_MODEM_CDMA_RM_PROTOCOL_PACKET_RELAY = 2
    MM_MODEM_CDMA_RM_PROTOCOL_PACKET_NETWORK_PPP = 3
    MM_MODEM_CDMA_RM_PROTOCOL_PACKET_NETWORK_SLIP = 4
    MM_MODEM_CDMA_RM_PROTOCOL_STU_III = 5


class MMModemContactsStorage(IntEnum):
    MM_MODEM_CONTACTS_STORAGE_UNKNOWN = 0
    MM_MODEM_CONTACTS_STORAGE_ME = 1
    MM_MODEM_CONTACTS_STORAGE_SM = 2
    MM_MODEM_CONTACTS_STORAGE_MT = 3


class MMModemLocationSource(IntEnum):
    MM_MODEM_LOCATION_SOURCE_NONE = 0
    MM_MODEM_LOCATION_SOURCE_3GPP_LAC_CI = 1 << 0
    MM_MODEM_LOCATION_SOURCE_GPS_RAW = 1 << 1
    MM_MODEM_LOCATION_SOURCE_GPS_NMEA = 1 << 2
    MM_MODEM_LOCATION_SOURCE_CDMA_BS = 1 << 3
    MM_MODEM_LOCATION_SOURCE_GPS_UNMANAGED = 1 << 4
    MM_MODEM_LOCATION_SOURCE_AGPS = 1 << 5


class MMModemLock(IntEnum):
    MM_MODEM_LOCK_UNKNOWN = 0
    MM_MODEM_LOCK_NONE = 1
    MM_MODEM_LOCK_SIM_PIN = 2
    MM_MODEM_LOCK_SIM_PIN2 = 3
    MM_MODEM_LOCK_SIM_PUK = 4
    MM_MODEM_LOCK_SIM_PUK2 = 5
    MM_MODEM_LOCK_PH_SP_PIN = 6
    MM_MODEM_LOCK_PH_SP_PUK = 7
    MM_MODEM_LOCK_PH_NET_PIN = 8
    MM_MODEM_LOCK_PH_NET_PUK = 9
    MM_MODEM_LOCK_PH_SIM_PIN = 10
    MM_MODEM_LOCK_PH_CORP_PIN = 11
    MM_MODEM_LOCK_PH_CORP_PUK = 12
    MM_MODEM_LOCK_PH_FSIM_PIN = 13
    MM_MODEM_LOCK_PH_FSIM_PUK = 14
    MM_MODEM_LOCK_PH_NETSUB_PIN = 15
    MM_MODEM_LOCK_PH_NETSUB_PUK = 16


class MMModemMode(IntEnum):
    MM_MODEM_MODE_NONE = 0
    MM_MODEM_MODE_CS = 1 << 0
    MM_MODEM_MODE_2G = 1 << 1
    MM_MODEM_MODE_3G = 1 << 2
    MM_MODEM_MODE_4G = 1 << 3
    MM_MODEM_MODE_ANY = 0xFFFFFFFF


class MMModemState(IntEnum):
    MM_MODEM_STATE_FAILED = -1
    MM_MODEM_STATE_UNKNOWN = 0
    MM_MODEM_STATE_INITIALIZING = 1
    MM_MODEM_STATE_LOCKED = 2
    MM_MODEM_STATE_DISABLED = 3
    MM_MODEM_STATE_DISABLING = 4
    MM_MODEM_STATE_ENABLING = 5
    MM_MODEM_STATE_ENABLED = 6
    MM_MODEM_STATE_SEARCHING = 7
    MM_MODEM_STATE_REGISTERED = 8
    MM_MODEM_STATE_DISCONNECTING = 9
    MM_MODEM_STATE_CONNECTING = 10
    MM_MODEM_STATE_CONNECTED = 11


class MMModemStateFailedReason(IntEnum):
    MM_MODEM_STATE_FAILED_REASON_NONE = 0
    MM_MODEM_STATE_FAILED_REASON_UNKNOWN = 1
    MM_MODEM_STATE_FAILED_REASON_SIM_MISSING = 2
    MM_MODEM_STATE_FAILED_REASON_SIM_ERROR = 3


class MMModemStateChangeReason(IntEnum):
    MM_MODEM_STATE_CHANGE_REASON_UNKNOWN = 0
    MM_MODEM_STATE_CHANGE_REASON_USER_REQUESTED = 1
    MM_MODEM_STATE_CHANGE_REASON_SUSPEND = 2
    MM_MODEM_STATE_CHANGE_REASON_FAILURE = 3


class MMModemPowerState(IntEnum):
    MM_MODEM_POWER_STATE_UNKNOWN = 0
    MM_MODEM_POWER_STATE_OFF = 1
    MM_MODEM_POWER_STATE_LOW = 2
    MM_MODEM_POWER_STATE_ON = 3


class MMModemPortType(IntEnum):
    MM_MODEM_PORT_TYPE_UNKNOWN = 1
    MM_MODEM_PORT_TYPE_NET = 2
    MM_MODEM_PORT_TYPE_AT = 3
    MM_MODEM_PORT_TYPE_QCDM = 4
    MM_MODEM_PORT_TYPE_GPS = 5
    MM_MODEM_PORT_TYPE_QMI = 6
    MM_MODEM_PORT_TYPE_MBIM = 7


class MMOmaFeature(IntEnum):
    MM_OMA_FEATURE_NONE = 0
    MM_OMA_FEATURE_DEVICE_PROVISIONING = 1 << 0
    MM_OMA_FEATURE_PRL_UPDATE = 1 << 1
    MM_OMA_FEATURE_HANDS_FREE_ACTIVATION = 1 << 2


class MMOmaSessionState(IntEnum):
    MM_OMA_SESSION_STATE_FAILED = -1
    MM_OMA_SESSION_STATE_UNKNOWN = 0
    MM_OMA_SESSION_STATE_STARTED = 1
    MM_OMA_SESSION_STATE_RETRYING = 2
    MM_OMA_SESSION_STATE_CONNECTING = 3
    MM_OMA_SESSION_STATE_CONNECTED = 4
    MM_OMA_SESSION_STATE_AUTHENTICATED = 5
    MM_OMA_SESSION_STATE_MDN_DOWNLOADED = 10
    MM_OMA_SESSION_STATE_MSID_DOWNLOADED = 11
    MM_OMA_SESSION_STATE_PRL_DOWNLOADED = 12
    MM_OMA_SESSION_STATE_MIP_PROFILE_DOWNLOADED = 13
    MM_OMA_SESSION_STATE_COMPLETED = 20


class MMOmaSessionStateFailedReason(IntEnum):
    MM_OMA_SESSION_STATE_FAILED_REASON_UNKNOWN = 0
    MM_OMA_SESSION_STATE_FAILED_REASON_NETWORK_UNAVAILABLE = 1
    MM_OMA_SESSION_STATE_FAILED_REASON_SERVER_UNAVAILABLE = 2
    MM_OMA_SESSION_STATE_FAILED_REASON_AUTHENTICATION_FAILED = 3
    MM_OMA_SESSION_STATE_FAILED_REASON_MAX_RETRY_EXCEEDED = 4
    MM_OMA_SESSION_STATE_FAILED_REASON_SESSION_CANCELLED = 5


class MMOmaSessionType(IntEnum):
    MM_OMA_SESSION_TYPE_UNKNOWN = 0
    MM_OMA_SESSION_TYPE_CLIENT_INITIATED_DEVICE_CONFIGURE = 10
    MM_OMA_SESSION_TYPE_CLIENT_INITIATED_PRL_UPDATE = 11
    MM_OMA_SESSION_TYPE_CLIENT_INITIATED_HANDS_FREE_ACTIVATION = 12
    MM_OMA_SESSION_TYPE_NETWORK_INITIATED_DEVICE_CONFIGURE = 20
    MM_OMA_SESSION_TYPE_NETWORK_INITIATED_PRL_UPDATE = 21
    MM_OMA_SESSION_TYPE_DEVICE_INITIATED_PRL_UPDATE = 30
    MM_OMA_SESSION_TYPE_DEVICE_INITIATED_HANDS_FREE_ACTIVATION = 31


class MMSmsPduType(IntEnum):
    MM_SMS_PDU_TYPE_UNKNOWN = 0
    MM_SMS_PDU_TYPE_DELIVER = 1
    MM_SMS_PDU_TYPE_SUBMIT = 2
    MM_SMS_PDU_TYPE_STATUS_REPORT = 3
    MM_SMS_PDU_TYPE_CDMA_DELIVER = 32
    MM_SMS_PDU_TYPE_CDMA_SUBMIT = 33
    MM_SMS_PDU_TYPE_CDMA_CANCELLATION = 34
    MM_SMS_PDU_TYPE_CDMA_DELIVERY_ACKNOWLEDGEMENT = 35
    MM_SMS_PDU_TYPE_CDMA_USER_ACKNOWLEDGEMENT = 36
    MM_SMS_PDU_TYPE_CDMA_READ_ACKNOWLEDGEMENT = 37


class MMSmsState(IntEnum):
    MM_SMS_STATE_UNKNOWN = 0
    MM_SMS_STATE_STORED = 1
    MM_SMS_STATE_RECEIVING = 2
    MM_SMS_STATE_RECEIVED = 3
    MM_SMS_STATE_SENDING = 4
    MM_SMS_STATE_SENT = 5


class MMSmsDeliveryState(IntEnum):
    # --------------- 3GPP specific errors ----------------------

    # Completed deliveries
    MM_SMS_DELIVERY_STATE_COMPLETED_RECEIVED = 0x00
    MM_SMS_DELIVERY_STATE_COMPLETED_FORWARDED_UNCONFIRMED = 0x01
    MM_SMS_DELIVERY_STATE_COMPLETED_REPLACED_BY_SC = 0x02

    # Temporary failures
    MM_SMS_DELIVERY_STATE_TEMPORARY_ERROR_CONGESTION = 0x20
    MM_SMS_DELIVERY_STATE_TEMPORARY_ERROR_SME_BUSY = 0x21
    MM_SMS_DELIVERY_STATE_TEMPORARY_ERROR_NO_RESPONSE_FROM_SME = 0x22
    MM_SMS_DELIVERY_STATE_TEMPORARY_ERROR_SERVICE_REJECTED = 0x23
    MM_SMS_DELIVERY_STATE_TEMPORARY_ERROR_QOS_NOT_AVAILABLE = 0x24
    MM_SMS_DELIVERY_STATE_TEMPORARY_ERROR_IN_SME = 0x25

    # Permanent failures
    MM_SMS_DELIVERY_STATE_ERROR_REMOTE_PROCEDURE = 0x40
    MM_SMS_DELIVERY_STATE_ERROR_INCOMPATIBLE_DESTINATION = 0x41
    MM_SMS_DELIVERY_STATE_ERROR_CONNECTION_REJECTED = 0x42
    MM_SMS_DELIVERY_STATE_ERROR_NOT_OBTAINABLE = 0x43
    MM_SMS_DELIVERY_STATE_ERROR_QOS_NOT_AVAILABLE = 0x44
    MM_SMS_DELIVERY_STATE_ERROR_NO_INTERWORKING_AVAILABLE = 0x45
    MM_SMS_DELIVERY_STATE_ERROR_VALIDITY_PERIOD_EXPIRED = 0x46
    MM_SMS_DELIVERY_STATE_ERROR_DELETED_BY_ORIGINATING_SME = 0x47
    MM_SMS_DELIVERY_STATE_ERROR_DELETED_BY_SC_ADMINISTRATION = 0x48
    MM_SMS_DELIVERY_STATE_ERROR_MESSAGE_DOES_NOT_EXIST = 0x49

    # Temporary failures that became permanent
    MM_SMS_DELIVERY_STATE_TEMPORARY_FATAL_ERROR_CONGESTION = 0x60
    MM_SMS_DELIVERY_STATE_TEMPORARY_FATAL_ERROR_SME_BUSY = 0x61
    MM_SMS_DELIVERY_STATE_TEMPORARY_FATAL_ERROR_NO_RESPONSE_FROM_SME = 0x62
    MM_SMS_DELIVERY_STATE_TEMPORARY_FATAL_ERROR_SERVICE_REJECTED = 0x63
    MM_SMS_DELIVERY_STATE_TEMPORARY_FATAL_ERROR_QOS_NOT_AVAILABLE = 0x64
    MM_SMS_DELIVERY_STATE_TEMPORARY_FATAL_ERROR_IN_SME = 0x65
    # Unknown, out of any possible valid value [0x00-0xFF]
    MM_SMS_DELIVERY_STATE_UNKNOWN = 0x100

    # --------------- 3GPP2 specific errors ----------------------

    # Network problems
    MM_SMS_DELIVERY_STATE_NETWORK_PROBLEM_ADDRESS_VACANT = 0x200
    MM_SMS_DELIVERY_STATE_NETWORK_PROBLEM_ADDRESS_TRANSLATION_FAILURE = 0x201
    MM_SMS_DELIVERY_STATE_NETWORK_PROBLEM_NETWORK_RESOURCE_OUTAGE = 0x202
    MM_SMS_DELIVERY_STATE_NETWORK_PROBLEM_NETWORK_FAILURE = 0x203
    MM_SMS_DELIVERY_STATE_NETWORK_PROBLEM_INVALID_TELESERVICE_ID = 0x204
    MM_SMS_DELIVERY_STATE_NETWORK_PROBLEM_OTHER = 0x205
    # Terminal problems
    MM_SMS_DELIVERY_STATE_TERMINAL_PROBLEM_NO_PAGE_RESPONSE = 0x220
    MM_SMS_DELIVERY_STATE_TERMINAL_PROBLEM_DESTINATION_BUSY = 0x221
    MM_SMS_DELIVERY_STATE_TERMINAL_PROBLEM_NO_ACKNOWLEDGMENT = 0x222
    MM_SMS_DELIVERY_STATE_TERMINAL_PROBLEM_DESTINATION_RESOURCE_SHORTAGE = 0x223
    MM_SMS_DELIVERY_STATE_TERMINAL_PROBLEM_SMS_DELIVERY_POSTPONED = 0x224
    MM_SMS_DELIVERY_STATE_TERMINAL_PROBLEM_DESTINATION_OUT_OF_SERVICE = 0x225
    MM_SMS_DELIVERY_STATE_TERMINAL_PROBLEM_DESTINATION_NO_LONGER_AT_THIS_ADDRESS = 0x226
    MM_SMS_DELIVERY_STATE_TERMINAL_PROBLEM_OTHER = 0x227
    # Radio problems
    MM_SMS_DELIVERY_STATE_RADIO_INTERFACE_PROBLEM_RESOURCE_SHORTAGE = 0x240
    MM_SMS_DELIVERY_STATE_RADIO_INTERFACE_PROBLEM_INCOMPATIBILITY = 0x241
    MM_SMS_DELIVERY_STATE_RADIO_INTERFACE_PROBLEM_OTHER = 0x242
    # General problems
    MM_SMS_DELIVERY_STATE_GENERAL_PROBLEM_ENCODING = 0x260
    MM_SMS_DELIVERY_STATE_GENERAL_PROBLEM_SMS_ORIGINATION_DENIED = 0x261
    MM_SMS_DELIVERY_STATE_GENERAL_PROBLEM_SMS_TERMINATION_DENIED = 0x262
    MM_SMS_DELIVERY_STATE_GENERAL_PROBLEM_SUPPLEMENTARY_SERVICE_NOT_SUPPORTED = 0x263
    MM_SMS_DELIVERY_STATE_GENERAL_PROBLEM_SMS_NOT_SUPPORTED = 0x264
    MM_SMS_DELIVERY_STATE_GENERAL_PROBLEM_MISSING_EXPECTED_PARAMETER = 0x266
    MM_SMS_DELIVERY_STATE_GENERAL_PROBLEM_MISSING_MANDATORY_PARAMETER = 0x267
    MM_SMS_DELIVERY_STATE_GENERAL_PROBLEM_UNRECOGNIZED_PARAMETER_VALUE = 0x268
    MM_SMS_DELIVERY_STATE_GENERAL_PROBLEM_UNEXPECTED_PARAMETER_VALUE = 0x269
    MM_SMS_DELIVERY_STATE_GENERAL_PROBLEM_USER_DATA_SIZE_ERROR = 0x26A
    MM_SMS_DELIVERY_STATE_GENERAL_PROBLEM_OTHER = 0x26B

    # Temporary network problems
    MM_SMS_DELIVERY_STATE_TEMPORARY_NETWORK_PROBLEM_ADDRESS_VACANT = 0x300
    MM_SMS_DELIVERY_STATE_TEMPORARY_NETWORK_PROBLEM_ADDRESS_TRANSLATION_FAILURE = 0x301
    MM_SMS_DELIVERY_STATE_TEMPORARY_NETWORK_PROBLEM_NETWORK_RESOURCE_OUTAGE = 0x302
    MM_SMS_DELIVERY_STATE_TEMPORARY_NETWORK_PROBLEM_NETWORK_FAILURE = 0x303
    MM_SMS_DELIVERY_STATE_TEMPORARY_NETWORK_PROBLEM_INVALID_TELESERVICE_ID = 0x304
    MM_SMS_DELIVERY_STATE_TEMPORARY_NETWORK_PROBLEM_OTHER = 0x305
    # Temporary terminal problems
    MM_SMS_DELIVERY_STATE_TEMPORARY_TERMINAL_PROBLEM_NO_PAGE_RESPONSE = 0x320
    MM_SMS_DELIVERY_STATE_TEMPORARY_TERMINAL_PROBLEM_DESTINATION_BUSY = 0x321
    MM_SMS_DELIVERY_STATE_TEMPORARY_TERMINAL_PROBLEM_NO_ACKNOWLEDGMENT = 0x322
    MM_SMS_DELIVERY_STATE_TEMPORARY_TERMINAL_PROBLEM_DESTINATION_RESOURCE_SHORTAGE = 0x323
    MM_SMS_DELIVERY_STATE_TEMPORARY_TERMINAL_PROBLEM_SMS_DELIVERY_POSTPONED = 0x324
    MM_SMS_DELIVERY_STATE_TEMPORARY_TERMINAL_PROBLEM_DESTINATION_OUT_OF_SERVICE = 0x325
    MM_SMS_DELIVERY_STATE_TEMPORARY_TERMINAL_PROBLEM_DESTINATION_NO_LONGER_AT_THIS_ADDRESS = 0x326
    MM_SMS_DELIVERY_STATE_TEMPORARY_TERMINAL_PROBLEM_OTHER = 0x327
    # Temporary radio problems
    MM_SMS_DELIVERY_STATE_TEMPORARY_RADIO_INTERFACE_PROBLEM_RESOURCE_SHORTAGE = 0x340
    MM_SMS_DELIVERY_STATE_TEMPORARY_RADIO_INTERFACE_PROBLEM_INCOMPATIBILITY = 0x341
    MM_SMS_DELIVERY_STATE_TEMPORARY_RADIO_INTERFACE_PROBLEM_OTHER = 0x342
    # Temporary general problems
    MM_SMS_DELIVERY_STATE_TEMPORARY_GENERAL_PROBLEM_ENCODING = 0x360
    MM_SMS_DELIVERY_STATE_TEMPORARY_GENERAL_PROBLEM_SMS_ORIGINATION_DENIED = 0x361
    MM_SMS_DELIVERY_STATE_TEMPORARY_GENERAL_PROBLEM_SMS_TERMINATION_DENIED = 0x362
    MM_SMS_DELIVERY_STATE_TEMPORARY_GENERAL_PROBLEM_SUPPLEMENTARY_SERVICE_NOT_SUPPORTED = 0x363
    MM_SMS_DELIVERY_STATE_TEMPORARY_GENERAL_PROBLEM_SMS_NOT_SUPPORTED = 0x364
    MM_SMS_DELIVERY_STATE_TEMPORARY_GENERAL_PROBLEM_MISSING_EXPECTED_PARAMETER = 0x366
    MM_SMS_DELIVERY_STATE_TEMPORARY_GENERAL_PROBLEM_MISSING_MANDATORY_PARAMETER = 0x367
    MM_SMS_DELIVERY_STATE_TEMPORARY_GENERAL_PROBLEM_UNRECOGNIZED_PARAMETER_VALUE = 0x368
    MM_SMS_DELIVERY_STATE_TEMPORARY_GENERAL_PROBLEM_UNEXPECTED_PARAMETER_VALUE = 0x369
    MM_SMS_DELIVERY_STATE_TEMPORARY_GENERAL_PROBLEM_USER_DATA_SIZE_ERROR = 0x36A
    MM_SMS_DELIVERY_STATE_TEMPORARY_GENERAL_PROBLEM_OTHER = 0x36B


class MMSmsStorage(IntEnum):
    MM_SMS_STORAGE_UNKNOWN = 0
    MM_SMS_STORAGE_SM = 1
    MM_SMS_STORAGE_ME = 2
    MM_SMS_STORAGE_MT = 3
    MM_SMS_STORAGE_SR = 4
    MM_SMS_STORAGE_BM = 5
    MM_SMS_STORAGE_TA = 6


class MMSmsValidityType(IntEnum):
    MM_SMS_VALIDITY_TYPE_UNKNOWN = 0
    MM_SMS_VALIDITY_TYPE_RELATIVE = 1
    MM_SMS_VALIDITY_TYPE_ABSOLUTE = 2
    MM_SMS_VALIDITY_TYPE_ENHANCED = 3


class MMSmsCdmaTeleserviceId(IntEnum):
    MM_SMS_CDMA_TELESERVICE_ID_UNKNOWN = 0x0000
    MM_SMS_CDMA_TELESERVICE_ID_CMT91 = 0x1000
    MM_SMS_CDMA_TELESERVICE_ID_WPT = 0x1001
    MM_SMS_CDMA_TELESERVICE_ID_WMT = 0x1002
    MM_SMS_CDMA_TELESERVICE_ID_VMN = 0x1003
    MM_SMS_CDMA_TELESERVICE_ID_WAP = 0x1004
    MM_SMS_CDMA_TELESERVICE_ID_WEMT = 0x1005
    MM_SMS_CDMA_TELESERVICE_ID_SCPT = 0x1006
    MM_SMS_CDMA_TELESERVICE_ID_CATPT = 0x1007


class MMSmsCdmaServiceCategory(IntEnum):
    MM_SMS_CDMA_SERVICE_CATEGORY_UNKNOWN = 0x0000
    MM_SMS_CDMA_SERVICE_CATEGORY_EMERGENCY_BROADCAST = 0x0001
    MM_SMS_CDMA_SERVICE_CATEGORY_ADMINISTRATIVE = 0x0002
    MM_SMS_CDMA_SERVICE_CATEGORY_MAINTENANCE = 0x0003
    MM_SMS_CDMA_SERVICE_CATEGORY_GENERAL_NEWS_LOCAL = 0x0004
    MM_SMS_CDMA_SERVICE_CATEGORY_GENERAL_NEWS_REGIONAL = 0x0005
    MM_SMS_CDMA_SERVICE_CATEGORY_GENERAL_NEWS_NATIONAL = 0x0006
    MM_SMS_CDMA_SERVICE_CATEGORY_GENERAL_NEWS_INTERNATIONAL = 0x0007
    MM_SMS_CDMA_SERVICE_CATEGORY_BUSINESS_NEWS_LOCAL = 0x0008
    MM_SMS_CDMA_SERVICE_CATEGORY_BUSINESS_NEWS_REGIONAL = 0x0009
    MM_SMS_CDMA_SERVICE_CATEGORY_BUSINESS_NEWS_NATIONAL = 0x000A
    MM_SMS_CDMA_SERVICE_CATEGORY_BUSINESS_NEWS_INTERNATIONAL = 0x000B
    MM_SMS_CDMA_SERVICE_CATEGORY_SPORTS_NEWS_LOCAL = 0x000C
    MM_SMS_CDMA_SERVICE_CATEGORY_SPORTS_NEWS_REGIONAL = 0x000D
    MM_SMS_CDMA_SERVICE_CATEGORY_SPORTS_NEWS_NATIONAL = 0x000E
    MM_SMS_CDMA_SERVICE_CATEGORY_SPORTS_NEWS_INTERNATIONAL = 0x000F
    MM_SMS_CDMA_SERVICE_CATEGORY_ENTERTAINMENT_NEWS_LOCAL = 0x0010
    MM_SMS_CDMA_SERVICE_CATEGORY_ENTERTAINMENT_NEWS_REGIONAL = 0x0011
    MM_SMS_CDMA_SERVICE_CATEGORY_ENTERTAINMENT_NEWS_NATIONAL = 0x0012
    MM_SMS_CDMA_SERVICE_CATEGORY_ENTERTAINMENT_NEWS_INTERNATIONAL = 0x0013
    MM_SMS_CDMA_SERVICE_CATEGORY_LOCAL_WEATHER = 0x0014
    MM_SMS_CDMA_SERVICE_CATEGORY_TRAFFIC_REPORT = 0x0015
    MM_SMS_CDMA_SERVICE_CATEGORY_FLIGHT_SCHEDULES = 0x0016
    MM_SMS_CDMA_SERVICE_CATEGORY_RESTAURANTS = 0x0017
    MM_SMS_CDMA_SERVICE_CATEGORY_LODGINGS = 0x0018
    MM_SMS_CDMA_SERVICE_CATEGORY_RETAIL_DIRECTORY = 0x0019
    MM_SMS_CDMA_SERVICE_CATEGORY_ADVERTISEMENTS = 0x001A
    MM_SMS_CDMA_SERVICE_CATEGORY_STOCK_QUOTES = 0x001B
    MM_SMS_CDMA_SERVICE_CATEGORY_EMPLOYMENT = 0x001C
    MM_SMS_CDMA_SERVICE_CATEGORY_HOSPITALS = 0x001D
    MM_SMS_CDMA_SERVICE_CATEGORY_TECHNOLOGY_NEWS = 0x001E
    MM_SMS_CDMA_SERVICE_CATEGORY_MULTICATEGORY = 0x001F
    MM_SMS_CDMA_SERVICE_CATEGORY_CMAS_PRESIDENTIAL_ALERT = 0x1000
    MM_SMS_CDMA_SERVICE_CATEGORY_CMAS_EXTREME_THREAT = 0x1001
    MM_SMS_CDMA_SERVICE_CATEGORY_CMAS_SEVERE_THREAT = 0x1002
    MM_SMS_CDMA_SERVICE_CATEGORY_CMAS_CHILD_ABDUCTION_EMERGENCY = 0x1003
    MM_SMS_CDMA_SERVICE_CATEGORY_CMAS_TEST = 0x1004
